name: CI - Build & Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start app (background)
        run: |
          nohup npm start > /tmp/app.log 2>&1

      - name: Wait for server to be ready
        run: |
          # Attend jusqu'à 60s que l’un des ports courants réponde
          npx -y wait-on -t 60000 http-get://127.0.0.1:3000

      - name: Test with curl
        run: |
          echo "Hitting ${{ steps.pick.outputs.url }}"
          curl -sS -D - "${{ steps.pick.outputs.url }}" -o /dev/null
